Change editor.wordHighlightStrongBackground
catppuccin/vscode pull request #45
Opened 2022-10-11 14:33 UTC by aproposts

Having both editor.wordHighlightStrongBackground and editor.selectionBackground set to the same value makes it impossible to see selections in the active token. Applying 50% opacity to the token highlight restores functionality; I haven't checked to see if this issue exists in the other palettes.

2022-10-23 03:18 UTC, sgoudham commented
Hey 👋 , Thanks for raising this PR!

As suggested in this comment: https://github.com/catppuccin/vscode/pull/49#issuecomment-1287988421

This PR should:
1. Modify the `index.ts` file and re-generate the JSON files. 
2. Change base branch to `catppuccin:dev` instead of `catppuccin:main`

2022-10-23 03:20 UTC, sgoudham requested changes
Hey 👋 , Thanks for raising this PR!

As suggested in this comment: https://github.com/catppuccin/vscode/pull/49#issuecomment-1287988421

This PR should:
1. Modify the `index.ts` file and re-generate the JSON files. 
2. Change base branch to `catppuccin:dev` instead of `catppuccin:main`

2022-10-27 06:42 UTC, nekowinston commented
@sgoudham should be good to merge now.

2022-10-27 06:46 UTC, nekowinston approved these changes

2022-10-27 06:54 UTC, sgoudham approved these changes
LGTM! Thanks for picking it up @nekowinston

2022-10-27 06:55 UTC, merged